### ISSUE TITLE
Missing px units make warnings to appear upon executing xfce4-panel -r

### ISSUE THREAD

**Issue by dagolinuxoid** [synvatto/gtk.css-xfce#2]
Hi there. You've inspired me to customize look of my xfce panel yet another time. Note: it's better to use `background` rather than `background-color` property in a *gtk.css* file for altering a panel, because some elements aren't gonna reflect changes. Anyway thank you. This is my result.  Cheers.
[![Picture-Editor.png](https://i.postimg.cc/MG6HqDg9/Picture-Editor.png)](https://postimg.cc/w1rgkhqN)

**Comment by meyzatech** [comment]
thanks for letting me know, I have updated the repo, have fun!
